// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"app/internal/components/layout"
)

func Home(postHogKey string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"space-y-4\" x-data=\"{ activeTab: &#39;jornada&#39; }\"><div class=\"border-gray-700 flex justify-center\"><nav class=\"inline-flex rounded-lg bg-gray-800 p-1.5 shadow-lg\" aria-label=\"Tabs\"><button @click=\"activeTab = &#39;jornada&#39;\" :class=\"activeTab === &#39;jornada&#39;\n\t\t\t\t\t\t\t? &#39;bg-blue-500 text-white shadow-sm&#39;\n\t\t\t\t\t\t\t: &#39;text-gray-300 hover:text-white hover:bg-gray-700&#39;\" class=\"px-6 py-2.5 text-sm font-medium rounded-md transition-all duration-200 ease-in-out\">Jornada</button> <button @click=\"activeTab = &#39;estadisticas&#39;\" :class=\"activeTab === &#39;estadisticas&#39;\n\t\t\t\t\t\t\t? &#39;bg-blue-500 text-white shadow-sm&#39;\n\t\t\t\t\t\t\t: &#39;text-gray-300 hover:text-white hover:bg-gray-700&#39;\" class=\"px-4 py-2.5 text-sm font-medium rounded-md transition-all duration-200 ease-in-out\">Estadísticas</button></nav></div><div x-show=\"activeTab === &#39;jornada&#39;\" x-transition><section><h2 class=\"text-2xl font-semibold mb-4\">Jornada actual</h2><div hx-get=\"/components/tables/matchday-predictions\" hx-trigger=\"load, every 1m\"><p>Cargando jornada actual...</p></div></section></div><div x-show=\"activeTab === &#39;estadisticas&#39;\" x-cloak x-transition><div class=\"space-y-8\"><section><h2 class=\"text-2xl font-semibold mb-4\">Puntos totales</h2><div hx-get=\"/components/tables/total-points\" hx-trigger=\"load\"><p>Cargando puntos totales...</p></div></section><section><h2 class=\"text-2xl font-semibold mb-4\">Puntos por jornada</h2><div hx-get=\"/components/tables/points-per-matchday\" hx-trigger=\"load\"><p>Cargando puntos por jornada...</p></div></section></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Layout("Quini", postHogKey, true).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
